### ISSUE TITLE
cm-14.1_Info

### ISSUE THREAD

**Issue by anomalchik** [anomalchik/android_kernel_xiaomi_msm8953#1]
Works:
- [x] boot
- [x] Displays
- [x] Touch
- [x] Touch keys
- [x] Boot reason
- [x] vibration
- [x] SIM
- [x] Hardware keys
- [x] LED
- [x] accelerometer
- [x] FM
- [x] WiFI
- [x] BT
- [x] Gps
- [x] Cameras
- [x] Sound
- [x] Fingerprint
- [x] flash on focus
- [x] IR LED

**Comment by anomalchik** [comment]
Redmi 4 Prime (markw)

**Comment by anomalchik** [comment]
**fixed:** touch keys and boot reason

**Comment by anomalchik** [comment]
**fixed:** Sound

**Comment by anomalchik** [comment]
Wifi and BT fixed in device tree

**Comment by anomalchik** [comment]
**Cameras:** problem in msm_sensor_init_subdev_Ioctl() https://github.com/anomalchik/android_kernel_xiaomi_msm8953/blob/cm-14.1/drivers/media/platform/msm/camera_v2/sensor/msm_sensor_init.c#L116
**Stock kernel values for this switch(cmd):** 
```
VIDIOC_MSM_SENSOR_INIT_CFG have value 3233830602; (IN HEX: C0C056CA)
switch(cmd) have value: -1061136694; (IN HEX: C0C056CA)

```
**This kernel values:**
```
VIDIOC_MSM_SENSOR_INIT_CFG have value 3234879178; (IN HEX: C0D056CA)
switch(cmd) have value: -1061398838: (IN HEX: C0BC56CA)
```

Probe steps in blob: libmmcamera2_sensor_modules.so sensor probe code(this is an example code): https://github.com/sethsong90/vendor_qcom_new/blob/879eb95b4bd4843e058b5ebae832f60d8afc7d73/vendor/qcom/proprietary/mm-camera/mm-camera2/media-controller/modules/sensors/module/sensor_init.c#L206

**Comment by anomalchik** [comment]
camera sensors is fixed. Disabled ir_cut, ir_led for markw

**Comment by anomalchik** [comment]
flashlight fixed

**Comment by anomalchik** [comment]
ir led working

**Comment by anomalchik** [comment]
Tested: fpc fixed.

**Comment by 3EleVen** [comment]
Hello,does everything goes well？

**Comment by anomalchik** [comment]
It seems like that. 
Tested only my device(Makrw): OS: Lineage 14.1, Panel - tianma, fingerprint - fpc. Should work on the other rev's.
Mido compilation not tested for now.

**Comment by 3EleVen** [comment]
Thanks for your hard work!!!

**Comment by 3EleVen** [comment]
goodix fingerprint doesn't work and can't record video . i don't know how to solve them, can u give me some advises？

**Comment by anomalchik** [comment]
This rom problem

**Comment by anomalchik** [comment]
Also there is a problem with ringtone.
I don't have enough free time.
At the moment the development is engaged @razziell
